- hosts: terraform-ansible
  tasks:
  - name: Criando arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Feito com terraform e ansible!</h1>
  - name: Criando servidor
    shell: "nohup busybox httpd -f -p 8080 &"
  - name: Instalando python3 e virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    #como root
    become: yes
  - name: Git Clone
    ansible.builtin.git:
      repo: https://github.com/alura-cursos/clientes-leo-api.git
      dest: /home/ubuntu/project
      version: master
  - name: Instalando dependencias com pip (Django e Django Rest)
    pip: 
      virtualenv: /home/ubuntu/venv
      name:
        - django
        - djangorestframework
  - name: Alterando host do settings
    lineinfile: 
      path: /home/ubuntu/project/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes

      #pip freeze - Listar os pacotes instalados
      #python manage.py runserver 0.0.0.0:8000 - Iniciar o Django