- hosts: terraform-ansible
  tasks:
  - name: Criando arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Feito com terraform e ansible!</h1>
  - name: Criando servidor
    shell: "nohup busybox httpd -f -p 8080 &"
  - name: Instalando python3 e virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    #como root
    become: yes
  - name: Instalando dependencias com pip (Django e Django Rest)
    pip: 
      virtualenv: /home/ubuntu/venv
      name:
        - django
        - djangorestframework
  - name: Verificando se o projeto esta em execucao      
    stat:
      path: /home/ubuntu/setup/settings.py
    register: projeto  
  - name: Iniciando o projeto
    shell: '. /home/ubuntu/venv/bin/activate; django-admin startproject setup /home/ubuntu/'
    when: not projeto.stat.exists
  - name: Alterando host do settings
    lineinfile: 
      path: /home/ubuntu/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes

      #pip freeze - Listar os pacotes instalados
      #python manage.py runserver 0.0.0.0:8000 - Iniciar o Django